// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fuse
List fuse(NumericVector beta0, NumericVector slope0, IntegerVector grp_size0);
RcppExport SEXP _fusedanova_fuse(SEXP beta0SEXP, SEXP slope0SEXP, SEXP grp_size0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slope0(slope0SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp_size0(grp_size0SEXP);
    rcpp_result_gen = Rcpp::wrap(fuse(beta0, slope0, grp_size0));
    return rcpp_result_gen;
END_RCPP
}
// fuse_old
DataFrame fuse_old(NumericVector x, NumericVector slopes, NumericVector ngroup);
RcppExport SEXP _fusedanova_fuse_old(SEXP xSEXP, SEXP slopesSEXP, SEXP ngroupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slopes(slopesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ngroup(ngroupSEXP);
    rcpp_result_gen = Rcpp::wrap(fuse_old(x, slopes, ngroup));
    return rcpp_result_gen;
END_RCPP
}
// get_slopes
NumericVector get_slopes(NumericVector& xm, IntegerVector& ngroup, std::string weights, double gamma, NumericMatrix& W);
RcppExport SEXP _fusedanova_get_slopes(SEXP xmSEXP, SEXP ngroupSEXP, SEXP weightsSEXP, SEXP gammaSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type xm(xmSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type ngroup(ngroupSEXP);
    Rcpp::traits::input_parameter< std::string >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(get_slopes(xm, ngroup, weights, gamma, W));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fusedanova_fuse", (DL_FUNC) &_fusedanova_fuse, 3},
    {"_fusedanova_fuse_old", (DL_FUNC) &_fusedanova_fuse_old, 3},
    {"_fusedanova_get_slopes", (DL_FUNC) &_fusedanova_get_slopes, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fusedanova(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
